site_name: BMWi Forecasting Tool
site_url: https://example.com/

nav:
    - Home: index.md
    - Getting Started:
        - Start Here: start/start.md
        - User Workflow: start/user.md
        - Quick Access: start/quick.md
        #- Site Map: start/map.md
    - Step-by-Step Guide:
        - Home page: steps/home.md
        - Data Prep page: steps/data_prep.md
        - Model page: steps/model.md
        - Error Analysis page: steps/error.md
    - Advanced Features: 
        - Technical Workflow: advanced/tech_flow.md
        - Installation and Setup: advanced/installation.md
        - Cleaner Class: advanced/cleanerclass.md
    - About:
        - Tool: about/tool.md
        - Team: about/team.md 
        - Licences: about/licenses.md
    - Our Journey: 
        - Models: journey/models.md
        - Clusters: journey/clusters.md
        - Causal Inference: journey/causal_inf.md

theme: readthedocs