site_name: BMWi Forecasting Tool
site_url: https://example.com/

nav:
    #- Home: index.md
    - First-Time Users: index.md
        #- User Profiles: first/users.md
        #- About: first/about.md
        #- Site Map: first/map.md
        #- User Workflow: first/workflow.md
    - Quick Access: quick.md
    - Step-by-Step Guide:
        - Home page: steps\home.md
        - Data Prep page: steps/data_prep.md
        - Model page: steps/model.md
        - Error Analysis page: steps\error.md
    - Advanced Features: 
        - Installation and Setup: advanced/installation.md
        - Cleaner Class: advanced/cleanerclass.md
    - About:
        - Tool: about/tool.md
        - Team: about/team.md 
        - Licences: about/licenses.md
    - Our Journey: 
        - Models: journey/models.md
        - Clusters: journey/clusters.md
        - Causal Inference: journey/causal_inf.md

theme: readthedocs